### ISSUE TITLE
RabbitMQ package - receiving messages

### ISSUE THREAD

**Issue by piersmacdonald** [golevelup/nestjs#163]
I have the following rabbitmq configuration:

This is my subscription function:

```
  @RabbitSubscribe({
    exchange: RabbitMqConsts.Exchanges.TransactionAccepted,
    routingKey: 'accepted.*',
    queue: RabbitMqConsts.Queues.SocketService.TransactionAccepted,
    queueOptions: {deadLetterExchange: 'DLQ'},
    errorHandler: handleError,
    allowNonJsonMessages: true,
  })
  public async subscribeTranactionAccepted(event: {}): Promise<void> {
    console.log(`EVENT ${JSON.stringify(event)}`);
  }
```

When I try to send message I see this error logged:

```
Cannot destructure property `path` of 'undefined' or 'null'.
    \nTypeError: Cannot destructure property `path` of 'undefined' or 'null'.\n  
      at CatchSubscriber.selector (C:\\workspace\\platform-api\\dist\\main.js:39420:28)\n  
        at CatchSubscriber.error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\operators\\catchError.js:48:31)\n    
        at MapSubscriber.Subscriber._error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\Subscriber.js:92:26)\n  
          at MapSubscriber.Subscriber.error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\Subscriber.js:72:18)\n  
            at MergeMapSubscriber.OuterSubscriber.notifyError (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\OuterSubscriber.js:26:26)\n    at InnerSubscriber._error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\InnerSubscriber.js:31:21)\n    at InnerSubscriber.Subscriber.error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\Subscriber.js:72:18)\n    at SwitchMapSubscriber.Subscriber._error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\Subscriber.js:92:26)\n    at SwitchMapSubscriber.Subscriber.error (C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\Subscriber.js:72:18)\n    at C:\\workspace\\platform-api\\node_modules\\rxjs\\internal\\util\\subscribeToPromise.js:10:43"
```

Adding an error handler like this:

```
const handleError = (
  channel: any,
  msg: any,
  error: any,
): void => {
  console.log(`${error.message}`);
};
```

produces this error:

`res.status is not a function`

I can't for the life of me track down if the error is in this package, `@nest/microservices`, `@nest/core`. Any ideas?

**Comment by WonderPanda** [comment]
@piersmacdonald I realize that this is is a super old issue. I apologize for not replying to it sooner. Based on the stack traces that you've shared my guess would be that you have a globally bound Interceptor that is attempting to do something with an HTTP request.

There's relatively new functionality and docs about this situation as other people have run into it before. See https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#usage-with-interceptors

If this doesn't help you out and you have more information about your issues feel free to re-open this
