### ISSUE TITLE
Infinite loop while throw Exception From service

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#199]
Found a bug while throw an exception from service with function that subscribe to a queue

reproducue:

1-  add the following function 

I have a service with the following function 👎 

```
  @RabbitSubscribe({
    exchange: 'test.ex'
    routingKey: 'test.#'
    queue: test.q
  })
  async handleMessage(message: any) {
      throw new Error('try this'); 
  }
```
or

```
  @RabbitSubscribe({
    exchange: 'test.ex'
    routingKey: 'test.#'
    queue: test.q
  })
  async handleMessage(message: any) {
     if(!message){. 
     throw new HttpException('test',500);  / 
  } 
  }
```

2. send message via ui managment for example : {"test":"message"}

result: infinite loop  ( event id its wrap by if)

stack trace 

```
Error: sdfd
    at TestService.handleInputScansUpdate (/...service.ts:26:13)
    at /node_modules/@nestjs/core/helpers/external-context-creator.js:71:29
    at InterceptorsConsumer.intercept (node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at target (node_modules/@nestjs/core/helpers/external-context-creator.js:76:60)
    at node_modules/@nestjs/core/helpers/external-proxy.js:9:30
    at AmqpConnection.handleMessage (/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:412:12)
    at channel.consume (node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:258:37)
    at ConfirmChannel.BaseChannel.dispatchMessage (/node_modules/amqplib/lib/channel.js:484:12)
    at ConfirmChannel.BaseChannel.handleDelivery (/node_modules/amqplib/lib/channel.js:493:15)
    at ConfirmChannel.emit (events.js:198:13)
    at ConfirmChannel.EventEmitter.emit (domain.js:448:20)
    at /node_modules/amqplib/lib/channel.js:279:10
    at ConfirmChannel.content (/node_modules/amqplib/lib/channel.js:332:9)
    at ConfirmChannel.C.acceptMessageFrame (//node_modules/amqplib/lib/channel.js:247:31)
    at ConfirmChannel.C.accept (node_modules/amqplib/lib/channel.js:400:17)
    at Connection.mainAccept [as accept] (node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitReadable_ (_stream_readable.js:539:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

I thought it because of the interceptor but also cancel it to make sure

**Comment by itzahi** [comment]
Hi 
For error handling you can use the errorHandler 

```
 @RabbitRPC({
    routingKey: 'error-reply-rpc',
    exchange: 'exchange1',
    queue: 'error-reply-rpc',
    errorHandler: ackErrorHandler,
  })
import {
  ackErrorHandler
} from '@golevelup/nestjs-rabbitmq';
```
that works for me

in addition you can create a custom handler like : ReplyErrorCallback 

example for a custom one :  
https://github.com/golevelup/nestjs/blob/master/integration/rabbitmq/src/rpc/reply.error.callback.ts 
the custom one can help you for logging and extra logic

``` 
@RabbitRPC({
    routingKey: 'error-reply-rpc',
    exchange: 'exchange1',
    queue: 'error-reply-rpc',
    errorHandler: ReplyErrorCallback,
  })


```

**Comment by WonderPanda** [comment]
@itzahi Thank you for helping to answer this. Providing an `errorHandler` is the correct way to deal with this situation
