### ISSUE TITLE
Cannot read property 'isConnected' of undefined

### ISSUE THREAD

**Issue by arthurgrigoletto** [golevelup/nestjs#246]
Hello, I'm trying to build microservices applications with a RabbitMQ connection. Am I doing something wrong?

main.ts
```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  await app.listen(3000);
  console.log(`Application is running on: ${await app.getUrl()}`);
}
bootstrap();
```

app.module.ts
```
import { Module } from '@nestjs/common';
import { UserModule } from './user/user.module';
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      uri: 'amqp://admin:admin@rabbitmq:5672',
      connectionInitOptions: { wait: false },
    }),
    UserModule
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}

```

user.module.ts
```
import { AmqpConnection } from '@golevelup/nestjs-rabbitmq';
import { Module } from '@nestjs/common';
import { CreateUserService } from './services/create-user.service';
import { UserController } from './user.controller';

@Module({
  imports: [
  ],
  controllers: [UserController],
  providers: [CreateUserService, AmqpConnection],
})
export class UserModule {}

```

service.
```
import { AmqpConnection } from "@golevelup/nestjs-rabbitmq";
import { Injectable } from '@nestjs/common';
import { v4 as uuid } from 'uuid';
import { CreateUserDTO } from '../dto/create-user.dto';

@Injectable()
export class CreateUserService {
  constructor(
    private amqpConn: AmqpConnection
  ) {}

  public async execute({ name }: CreateUserDTO) {
    const user = {
      id: uuid(),
      name,
    };
    this.amqpConn.publish(
      'amq.direct',
      'create-user-accounts',
      user
    );

    return user;
  }
}

```

Result

```
(node:840) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isConnected' of undefined
    at AmqpConnection.publish (/home/node/app/node_modules/@golevelup/nestjs-rabbitmq/lib/amqp/connection.js:191:37)
    at CreateUserService.execute (/home/node/app/dist/user/services/create-user.service.js:25:23)
    at UserController.create (/home/node/app/dist/user/user.controller.js:39:39)
    at /home/node/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/node/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /home/node/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can anyone help me out?

Thanks

**Comment by WonderPanda** [comment]
@arthurgrigoletto You should not add `AmqpConnection` to your providers. It is already provided from the RabbitMQ module. If you want to use the AMQP behavior across multiple modules you should create a wrapper Module that does `RabbitMQModule.forRoot` and then export the entire RabbitMQ Module so make all the dependencies available to any of the other modules in your app

**Comment by arthurgrigoletto** [comment]
Thank's @WonderPanda, it worked for me :)

**Comment by Mi-lex** [comment]
> @arthurgrigoletto You should not add `AmqpConnection` to your providers. It is already provided from the RabbitMQ module. If you want to use the AMQP behavior across multiple modules you should create a wrapper Module that does `RabbitMQModule.forRoot` and then export the entire RabbitMQ Module so make all the dependencies available to any of the other modules in your app

Can you write a brief example of such module ? Did not quite get how I can export entire module.
I wrote something like this:

```typescript
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';
import { Global, Module } from '@nestjs/common';
import { ConfigModule, ConfigService, ConfigType } from '@nestjs/config';
import { rabbitConfig } from '../../config';
import { DEFAULT_RABBIT_EXCHANGE } from '../../config/constants';

@Global()
@Module({
  imports: [
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => {
        const amqConfig =
          configService.get<ConfigType<typeof rabbitConfig>>('rabbit');

        return {
          exchanges: [
            {
              name: DEFAULT_RABBIT_EXCHANGE,
              type: 'x-delayed-message',
            },
          ],
          // eslint-disable-next-line @typescript-eslint/no-non-null-asserted-optional-chain
          uri: amqConfig?.URL!,
          connectionInitOptions: { wait: false },
        };
      },
      inject: [ConfigService],
    }),
  ],
  exports: [RabbitMQModule],
})
export class RabbitModule {}

```

I assume that is not what u meant.
