### ISSUE TITLE
Frame size exceeds frame max

### ISSUE THREAD

**Issue by schealex** [golevelup/nestjs#408]
Hi guys,

i'm trying to use the awesome rabbitmq module with Amazon MQ (RabbitMQ 3.9.13) and i'm getting this error once the service tries to connect:

```
←[32m[Nest] 29  - ←[39m03/17/2022, 6:56:47 PM ←[32m    LOG←[39m ←[38;5;3m[AmqpConnection] ←[39m←[32mTrying to connect to a RabbitMQ broker←[39m
←[31m[Nest] 29  - ←[39m03/17/2022, 6:56:47 PM ←[31m  ERROR←[39m ←[38;5;3m[AmqpConnection] ←[39m←[31mDisconnected from RabbitMQ broker←[39m
Error: Frame size exceeds frame max
    at parseFrame (/usr/src/app/node_modules/amqplib/lib/frame.js:56:13)
    at Connection.C.recvFrame (/usr/src/app/node_modules/amqplib/lib/connection.js:605:15)
    at Connection.C.recvFrame (/usr/src/app/node_modules/amqplib/lib/connection.js:615:19)
    at Socket.recv (/usr/src/app/node_modules/amqplib/lib/connection.js:493:16)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:400:28)
    at emitReadable_ (internal/streams/readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
From previous event:
    at Object.connect (/usr/src/app/node_modules/amqplib/channel_api.js:6:18)
    at /usr/src/app/node_modules/@golevelup/nestjs-rabbitmq/node_modules/amqp-connection-manager/dist/cjs/AmqpConnectionManager.js:242:38
←[31m[Nest] 29  - ←[39m03/17/2022, 6:56:47 PM ←[31m  ERROR←[39m ←[38;5;3m[ExceptionHandler] ←[39m←[31mFailed to connect to a RabbitMQ broker within a timeout of 3000ms←[39m
Error: Failed to connect to a RabbitMQ broker within a timeout of 3000ms
    at /usr/src/app/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:135:17
    at Observable.init [as _subscribe] (/usr/src/app/node_modules/rxjs/src/internal/observable/throwError.ts:123:68)
    at Observable._trySubscribe (/usr/src/app/node_modules/rxjs/src/internal/Observable.ts:245:19)
    at /usr/src/app/node_modules/rxjs/src/internal/Observable.ts:235:18
    at Object.errorContext (/usr/src/app/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Observable.subscribe (/usr/src/app/node_modules/rxjs/src/internal/Observable.ts:221:5)
    at /usr/src/app/node_modules/rxjs/src/internal/operators/timeout.ts:354:15
    at AsyncAction.<anonymous> (/usr/src/app/node_modules/rxjs/src/internal/util/executeSchedule.ts:27:5)
    at AsyncAction._execute (/usr/src/app/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:116:12)
    at AsyncAction.execute (/usr/src/app/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:91:24)
    at AsyncScheduler.flush (/usr/src/app/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:39:27)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

this is my module setup:

```ts
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      inject: [ConfigService],
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        exchanges: [
          {
            name: 'exchangename',
            type: 'topic',
          },
        ],
        defaultExchangeType: 'TOPIC',
        uri: `amqp://${configService.get<string>(
          'RMQ_USERNAME',
        )}:${configService.get<string>(
          'RMQ_PASSWORD',
        )}@${configService.get<string>('RMQ_HOST')}:${configService.get<number>(
          'RMQ_PORT',
        )}`,
        connectionInitOptions: { wait: true, reject: true, timeout: 3000 },
      }),
    }),
```

Hope someone can help me on this because this is blocking my deployment right now :/

Regards
Alex

**Comment by schealex** [comment]
nvm. fixed it. but for others stepping on this i was using amqp as protocol where AWS requires amqps. That was all.

**Comment by viniciusz42** [comment]
Just be clear: just change your connection string to amqp:// to amqp**s**:://

**Comment by javiermrz** [comment]
You saved my life ❤️
