### ISSUE TITLE
Unable to use assertQueueErrorHandler: Channel ended

### ISSUE THREAD

**Issue by buffcode** [golevelup/nestjs#413]
I am trying to (re-)configure a queue and add a dead letter exchange. Therefore I added `assertQueueErrorHandler: forceDeleteAssertQueueErrorHandler` as implemented by #348.

Unfortunately this still crashes, as the channel is closed as soon as the queue assertion fails:
```
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'node_messages' in vhost '/': received the value 'node_messages_delays' of type 'longstr' but current is none"
    at ConfirmChannel.C.accept (/var/www/instances/x/node-server/dist/node-server.js:79609:17)
    at Connection.mainAccept (/var/www/instances/x/node-server/dist/node-server.js:60998:33)
    at Socket.go (/var/www/instances/x/node-server/dist/node-server.js:61412:48)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at emitReadable_ (internal/streams/readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Unhandled rejection Error: Channel ended, no reply will be forthcoming
    at rej (/var/www/instances/x/node-server/dist/node-server.js:79388:7)
    at ConfirmChannel.C._rejectPending (/var/www/instances/x/node-server/dist/node-server.js:79394:42)
    at ConfirmChannel.C.toClosed (/var/www/instances/x/node-server/dist/node-server.js:79358:8)
    at Connection.C._closeChannels (/var/www/instances/x/node-server/dist/node-server.js:61328:18)
    at Connection.C.toClosed (/var/www/instances/x/node-server/dist/node-server.js:61335:8)
    at Connection.C.onSocketError (/var/www/instances/x/node-server/dist/node-server.js:61289:10)
    at Connection.emit (events.js:400:28)
    at Connection.emit (domain.js:475:12)
    at Socket.go (/var/www/instances/x/node-server/dist/node-server.js:61415:12)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at emitReadable_ (internal/streams/readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Is this feature subject to a specific RabbitMQ version (3.7.28) or configuration?

<details>
<summary>Queue configuration</summary>

```js
      {
        exchange: exchangeQueue,
        queueOptions: {
          durable: true,
          deadLetterExchange: `${queueName}_delays`,
        },
        routingKey: queueName,
        queue: queueName,
        createQueueIfNotExists: true,
        assertQueueErrorHandler: forceDeleteAssertQueueErrorHandler,
      },
```
</details>

**Comment by underfisk** [comment]
@buffcode Be sure that your queue is empty in RMQ because otherwise the configurations are different and that might cause this. If your instance is already brand new then just provide us a repo to replicate this

**Comment by Fgruntjes** [comment]
@buffcode it has been a while, but we are experiencing the same issue. The answer of @underfisk does not really change the situation, the whole point of the feature is to recreate the queue whenever some configurations change. That is currently not possible because the channel has already been closed.

We are registering the handlers ourselves, so we can do this with a new connection object.
```
config.assertQueueErrorHandler = async (
    channel: Channel,
    queueName: string,
    queueOptions: QueueOptions | undefined,
    error: AmqpError
) => {
    const newChannel = connection.managedChannel;
    if (error.code === 406) {
        //406 == preconditions failed
        await newChannel.deleteQueue(queueName);
        const { queue } = await newChannel.assertQueue(queueName, queueOptions);
        return queue;
    }
    throw error;
};
```
