### ISSUE TITLE
Self Signed Certificate Exception

### ISSUE THREAD

**Issue by doronmakela** [golevelup/nestjs#448]
hello, I'm having an issue with setting up a TLS connection with a private certificate using rabbitmq module.

the error I got is 
`[Nest] 57395  - 08/06/2022, 12:22:36   ERROR [AmqpConnection] Disconnected from RabbitMQ broker (default)
Error: self signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12)`

and finally got an timeout error
`[Nest] 57395  - 08/06/2022, 12:22:40   ERROR [ExceptionHandler] Failed to connect to a RabbitMQ broker within a timeout of 5000ms
Error: Failed to connect to a RabbitMQ broker within a timeout of 5000ms
    at /home/code/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:140:17
    at Observable.init [as _subscribe] (/home/code/node_modules/rxjs/src/internal/observable/throwError.ts:123:68)
    at Observable._trySubscribe (/home/code/node_modules/rxjs/src/internal/Observable.ts:245:19)
    at /home/code/node_modules/rxjs/src/internal/Observable.ts:235:18
    at Object.errorContext (/home/code//node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Observable.subscribe (/home/code/node_modules/rxjs/src/internal/Observable.ts:221:5)
    at /home/code/node_modules/rxjs/src/internal/operators/timeout.ts:354:15
    at AsyncAction.<anonymous> (/home/code/node_modules/rxjs/src/internal/util/executeSchedule.ts:27:5)
    at AsyncAction._execute (/home/code/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:116:12)
    at AsyncAction.execute (/home/code/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:91:24)
    at AsyncScheduler.flush (/home/code/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:39:27)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)`

I load the cert.pem file using the connectionManagerOptions object - config.cert is buffer of pem file
`      connectionManagerOptions: { connectionOptions: { cert: config.cert } },`

when I set the NODE_TLS_REJECT_UNAUTHORIZED to 0 it is working perfectly.

thanks!

**Comment by underfisk** [comment]
@doronmakela It isn't related to the `@golevelup` rabbitmq package therefore i advice you to look into https://github.com/jwalton/node-amqp-connection-manager and https://amqp-node.github.io/amqplib/
