### ISSUE TITLE
got Cannot read properties of undefined (reading 'authorization') when handle a message with @RabbitSubscribe

### ISSUE THREAD

**Issue by AhmadZuhdi** [golevelup/nestjs#467]
i have a 1 backend with that act as producer (publish) and consumer (RabbitSubscribe)

producer:
```typescript
    this.amqpConnection.publish(
      'exchange1',
      'game-coordinator/update-state',
      {
        roomId: createRoomPlayerDto.roomsId,
      },
      {
        headers: {}
      },
    );
```

consumer:
```typescript
  @RabbitSubscribe({
    exchange: 'exchange1',
    routingKey: 'game-coordinator/update-state',
    queue: 'game-coordinator-queue',
  })
  async updateGameState(msg) {
    return new Nack();
  }
```

but when i enable the @RabbitSubscribe i got this error
```
[1657017946766] ERROR (33113 on Ahmads-MacBook-Pro.local):
    context: "ExceptionsHandler"
    err: {
      "type": "Error",
      "message": "Cannot read properties of undefined (reading 'authorization')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'authorization')
              at JwtStrategy._jwtFromRequest (/root_project/node_modules/passport-jwt/lib/extract_jwt.js:58:28)
              at JwtStrategy.authenticate (/root_project/node_modules/passport-jwt/lib/strategy.js:93:22)
              at attempt (/root_project/node_modules/passport/lib/middleware/authenticate.js:366:16)
              at authenticate (/root_project/node_modules/passport/lib/middleware/authenticate.js:367:7)
              at /root_project/node_modules/@nestjs/passport/dist/auth.guard.js:96:3
              at new Promise (<anonymous>)
              at /root_project/node_modules/@nestjs/passport/dist/auth.guard.js:88:83
              at JwtAuthGuard.<anonymous> (/root_project/node_modules/@nestjs/passport/dist/auth.guard.js:49:36)
              at Generator.next (<anonymous>)
              at fulfilled (/root_project/node_modules/@nestjs/passport/dist/auth.guard.js:17:58)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }

```

is there any missing step that i miss to implement ?

**Comment by WonderPanda** [comment]
It looks like you probably have some kind of Auth interceptor that is configured to run for all handlers. Are you able to refer to the docs and conditionally disable this for your RabbitMQ handlers?

**Comment by AhmadZuhdi** [comment]
ah okay, let me check

**Comment by AhmadZuhdi** [comment]
okay, when i add `@Public` above the `@RabbitSubscribe`, the problem is gone
