### ISSUE TITLE
kitchen-sink unit tests failing 

### ISSUE THREAD

**Issue by patrick-fitzgerald** [golevelup/nestjs#50]
Hi, I'm seeing some test failures when running `npm test` in the kitchen-sink example directory.

I've added these dependencies to make the project run:
```
  "dependencies": {
    "@nestjs-plus/common": "^1.1.0",
    "@nestjs-plus/rabbitmq": "^1.4.1",
```

Test results:
```
 PASS  src/app.controller.spec.ts
 PASS  src/rabbit-example/messaging/messaging.service.spec.ts (5.057s)
 FAIL  src/rabbit-example/messaging/messaging.controller.spec.ts (5.084s)
  ● Messaging Controller › should be defined

    Nest can't resolve dependencies of the MessagingController (?). Please make sure that the argument AmqpConnection at index [0] is available in the _RootTestModule context.

    Potential solutions:
    - If AmqpConnection is a provider, is it part of the current _RootTestModule?
    - If AmqpConnection is exported from a separate @Module, is that module imported within _RootTestModule?
      @Module({
        imports: [ /* the Module containing AmqpConnection */ ]
      })

      at Injector.lookupComponentInExports (../node_modules/@nestjs/core/injector/injector.js:183:19)

  ● Messaging Controller › should be defined

    expect(received).toBeDefined()

    Received: undefined

      14 | 
      15 |   it('should be defined', () => {
    > 16 |     expect(controller).toBeDefined();
         |                        ^
      17 |   });
      18 | });
      19 | 

      at Object.it (rabbit-example/messaging/messaging.controller.spec.ts:16:24)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        5.505s
Ran all test suites.
```

Let me know how if there's a way to fix the tests?

Thanks,
Patrick

**Comment by WonderPanda** [comment]
@patrickandroid I've fixed this. In general I've not put an effort into keeping the tests in the KitchenSink up to date as they're just the default scaffolded ones that come with a new Nest app. The actual tests (both unit and integration) which are run in Travis are all kept alongside the actual library code

**Comment by patrick-fitzgerald** [comment]
Thanks
