### ISSUE TITLE
rxjs_1.lastValueFrom is not a function

### ISSUE THREAD

**Issue by andreaskas** [golevelup/nestjs#501]
Hello,

I have installed the latest version 3.2.0 and rxjs is also defined as ^7.5.6 but when i am trying to start nest i am getting the following error:

`TypeError: (0 , rxjs_1.lastValueFrom) is not a function
    at AmqpConnection.init (/project/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:183:25)
    at Function.AmqpConnectionFactory (/project/node_modules/@golevelup/nestjs-rabbitmq/src/rabbitmq.module.ts:84:22)
    at InstanceWrapper.useFactory [as metatype] (/project/node_modules/@golevelup/nestjs-rabbitmq/src/rabbitmq.module.ts:43:34)
    at Injector.instantiateClass (/project/node_modules/@nestjs/core/injector/injector.js:343:55)
    at callback (/project/node_modules/@nestjs/core/injector/injector.js:53:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Injector.resolveConstructorParams (/project/node_modules/@nestjs/core/injector/injector.js:132:24)
    at Injector.loadInstance (/project/node_modules/@nestjs/core/injector/injector.js:57:13)
    at Injector.loadProvider (/project/node_modules/@nestjs/core/injector/injector.js:84:9)
    at async Promise.all (index 4)
    at InstanceLoader.createInstancesOfProviders (/project/node_modules/@nestjs/core/injector/instance-loader.js:47:9)
    at /project/node_modules/@nestjs/core/injector/instance-loader.js:32:13
    at async Promise.all (index 19)
    at InstanceLoader.createInstances (/project/node_modules/@nestjs/core/injector/instance-loader.js:31:9)
    at InstanceLoader.createInstancesOfDependencies (/project/node_modules/@nestjs/core/injector/instance-loader.js:21:9)
    at /project/node_modules/@nestjs/core/nest-factory.js:96:17`

I was using nestjs v8 and upgraded to v9 as well but the problem remains. All nestjs components are aligned on the versions (either v8 or v9) and as already mentioned rxjs is on version 7.5.6. Also the specified function that the error refers to, is being used on my other parts of my code without any problem.

Any feedback would be appreciated.

Thanks

**Comment by andreaskas** [comment]
I think the problem is related to #476 setting manually rxjs dependency to version 7 seems to solve my problem.
