### ISSUE TITLE
Missing stripe webhook secret

### ISSUE THREAD

**Issue by twigs67** [golevelup/nestjs#553]
I'm getting the following error: 
```
missing stripe webhook secret. module is improperly configured and will be unable to process incoming webhooks from Stripe
Error: missing stripe webhook secret. module is improperly configured and will be unable to process incoming webhooks from Stripe
    at StripeModule.onModuleInit (/Users/alex.flores/MakerSoftware/formpiper-api/node_modules/@golevelup/nestjs-stripe/src/stripe.module.ts:96:13)
    at callModuleInitHook (/Users/alex.flores/MakerSoftware/formpiper-api/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NestApplication.callInitHook (/Users/alex.flores/MakerSoftware/formpiper-api/node_modules/@nestjs/core/nest-application-context.js:227:13)
    at async NestApplication.init (/Users/alex.flores/MakerSoftware/formpiper-api/node_modules/@nestjs/core/nest-application.js:98:9)
    at async NestApplication.listen (/Users/alex.flores/MakerSoftware/formpiper-api/node_modules/@nestjs/core/nest-application.js:168:33)
    at async bootstrap (/Users/alex.flores/MakerSoftware/formpiper-api/projects/server/src/main.ts:145:18)

```
Code:
```
/// AppModule
    StripeModule.forRoot(StripeModule, {
      apiKey: process.env.STRIPE_SECRET,
      apiVersion: '2022-11-15',
      webhookConfig: {
        stripeWebhookSecret: process.env.STRIPE_ENDPOINT_SECRET,
      },
    }),
...
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    applyRawBodyOnlyTo(consumer, {
      method: RequestMethod.ALL,
      path: 'webhook/stripe',
    });
  }
}

```
Packages:
```
"stripe": "^11.9.1",
"@golevelup/nestjs-stripe": "^0.5.0",
"@golevelup/nestjs-webhooks": "^0.2.14",
```

I have tried `forRootAsync` with `ConfigModule` calling the envs, but I still get the same error message.

**Comment by twigs67** [comment]
Deleting `node_modules` and my `dist` dir seemed to have worked.
