### ISSUE TITLE
Reading a property of undefined in AmqpConnection`s constructor 

### ISSUE THREAD

**Issue by VarTony** [golevelup/nestjs#637]
Hi.
When accessing the configs property logger, the following error occurred: 
`TypeError: Cannot read properties of undefined (reading 'logger')
at new AmqpConnection (/Users/.../auth-service/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:132:22)`

All I did was add `AmqpConnection` to my module's providers.

With decorators like `@RabbitRPC({...})` everything works fine.

This is my connection module: 

```
@Module({
  imports: [
    TypeOrmModule.forFeature([ Secret ]),
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      
      useFactory: async (config: ConfigService) => {
        const login = config.get('amqLogin');
        const pass = config.get('amqPass');
        const host = ‘${ config.get('amqHost') }:${ config.get('amqPort') }’;
        const domainExchange = config.get('amqDomainExchange');

        const exchanges = [ { name: domainExchange, type: 'topic' } ];
        
        const uri = `amqp://${ login }:${ pass }@${ host }`;
        const connectionInitOptions = { wait: false };
        return { exchanges, uri, connectionInitOptions };
      },
      inject: [ConfigService],
    }),
  ],
    controllers: [ SecretController ],
    providers: [ SecretService, SecretController ]
})
```

What could be the problem?

**Comment by maximing** [comment]
I have the same problem.
Just add AmqpConnection to my module providers section.


```
import { AmqpConnection, RabbitMQModule } from '@golevelup/nestjs-rabbitmq';
import { Module } from '@nestjs/common';

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {...}),
    MetricsModule,
  ],
  providers: [AmqpConnection],
  controllers: [],
  exports: [],
})
export class RmqModule {}
```


```
TypeError: Cannot read properties of undefined (reading 'logger')
    at new AmqpConnection (.../node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:135:22)
```

**Comment by mogilevtsevdmitry** [comment]
Faced the same problem, it turned out that one of the modules in the imports was using AmqpConnection, although you only need to import the module in which RabbitMQModule is imported and configured. The main thing is not to forget to then export RabbitMQModule. Here is my config and it works, I just use this module globally and AmqpConnection is available for me everywhere.
```ts
@Global()
@Module({
    imports: [RabbitMQModule.forRootAsync(RabbitMQModule, AMQP_CONNECTION_FACTORY('amqp'))],
    exports: [RabbitMQModule],
    providers: [RabbitRpcParamsFactory],
})
export class AmqpModule {}
```
```ts
export const AMQP_CONNECTION_FACTORY = (configIdent: string) => ({
    useFactory: (configService: ConfigService) => {
        const amqpConfig = configService.get<RabbitMQConfig>(configIdent);
        if (!amqpConfig) {
            throw new Error('amqpConfig is empty. ' + configIdent);
        }
        return amqpConfig;
    },
    inject: [ConfigService],
});
```
```ts
const AMQP_CONFIG_EXCHANGES: RabbitMQExchangeConfig[] = [
    {
        name: 'test',
        type: 'direct',
    },
];

export const AMQP_CONFIG = registerAs(
    'amqp',
    (): RabbitMQConfig => ({
        uri: [process.env.AMQP_URI].filter((amqpUrl) => !!amqpUrl),
        exchanges: AMQP_CONFIG_EXCHANGES,
        connectionInitOptions: { wait: false },
        connectionManagerOptions: {
            heartbeatIntervalInSeconds: 15,
            reconnectTimeInSeconds: 30,
        },
    }),
);
```

**Comment by maximing** [comment]
@mogilevtsevdmitry Thanks, solution with `@Global()` works fine 👍

**Comment by WonderPanda** [comment]
Thanks for sharing your setup @mogilevtsevdmitry

I definitely think that for a lot of people creating a Global module to make the AmqpConnection available across the app is desireable
