### ISSUE TITLE
AmqpConnection

### ISSUE THREAD

**Issue by vanetec** [golevelup/nestjs#871]
Error: Cannot read properties of undefined (reading  'logger')

**Comment by underfisk** [comment]
@vane-tec We'll need more information such as a stacktrace or if you'd like to produce a repro in GH

**Comment by AckerApple** [comment]
@underfisk I have been dealing with this issue for sometime too, when upgrading from NestJs 9 to 10

In some of my tests, I have been able to fix by adding the following code:
```ts
.overrideProvider(AmqpConnection)
      .useValue(new AmqpConnection({ uri: '', logger: new ConsoleLogger() })) // Adjust as needed
```

However, ultimately I cannot solve every case of this AmqpConnection logger issue. We use a customer logger where I use NestJs


```ts
TypeError: Cannot read properties of undefined (reading 'logger')
        at new AmqpConnection (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:144:22)
        at Injector.instantiateClass (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/injector.js:365:19)
        at callback (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/injector.js:65:45)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at Injector.resolveConstructorParams (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/injector.js:144:24)
        at Injector.loadInstance (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/injector.js:70:13)
        at Injector.loadProvider (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/injector.js:97:9)
        at /Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/instance-loader.js:56:13
        at async Promise.all (index 8)
        at InstanceLoader.createInstancesOfProviders (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
        at /Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/instance-loader.js:40:13
        at async Promise.all (index 15)
        at InstanceLoader.createInstances (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/instance-loader.js:39:9)
        at InstanceLoader.createInstancesOfDependencies (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/injector/instance-loader.js:22:13)
        at /Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/nest-factory.js:108:17
        at Function.asyncRun (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
        at NestFactoryStatic.initialize (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/nest-factory.js:106:13)
        at NestFactoryStatic.create (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@nestjs/core/nest-factory.js:42:9)
        at NestQuick.boot (/Users/ackerapple/projects/bstock/3mp/methods/node_modules/@b-stock/src/nest-quick/NestQuick.class.ts:29:13)
        at getApp (/Users/ackerapple/projects/bstock/3mp/methods/src/index.app.ts:67:19)
        at start (/Users/ackerapple/projects/bstock/3mp/methods/src/app.test.utils.ts:24:22)
        at Object.<anonymous> (/Users/ackerapple/projects/bstock/3mp/methods/src/entities/entities.controller.spec.int.ts:33:25)

      at Function.asyncRun (../node_modules/@nestjs/core/errors/exceptions-zone.js:30:21)
```

**Comment by AckerApple** [comment]
I see someone else had some logger "issues" that I think maybe related #663 as well as #636

Some folks seemed to figure out how to work around it in #637 but I have not yet solved for myself

**Comment by AckerApple** [comment]
This line of code in `connection.js` needs to be corrected @underfisk 

FROM

```js
this.config = Object.assign(Object.assign({ deserializer: (message) => JSON.parse(message.toString()), serializer: (value) => Buffer.from(JSON.stringify(value)), logger: config.logger || new common_1.Logger(AmqpConnection.name) }, defaultConfig), config);
```

INTO

```js
this.config = Object.assign(Object.assign({ deserializer: (message) => JSON.parse(message.toString()), serializer: (value) => Buffer.from(JSON.stringify(value)), logger: config?.logger || new common_1.Logger(AmqpConnection.name) }, defaultConfig), config);
```

The change is to make config options optional as seen here `logger: config?.logger || new common_1.Logger(AmqpConnection.name)`

**Comment by underfisk** [comment]
@AckerApple Are you changing the typescript output?

**Comment by AckerApple** [comment]
I think the answer is yes, that in order to solve my issue, I have to edit the js file

At runtime I have no constructor arguments for `class AmqpConnection` so the constructor errors because config is not defined

The following file passes no config to the `new AmqpConnection()`: `node_modules/@nestjs/core/injector/injector.js`. Please see attached screen shot

I'm stuck at the moment unless I hand edit adding a question mark as such `logger: config?.logger`  but that only works locally and will fail on any installs

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/8872b533-93b9-4f8c-8ded-8c81e5e69945">

**Comment by underfisk** [comment]
@AckerApple Would you be willing to contribute with a PR to provide the actual fix?

**Comment by AckerApple** [comment]
I might be able to, its a one character change. Working on it right now

**Comment by underfisk** [comment]
Thank you! Feel free to add/update test coverage as that will help us preventing any regression

**Comment by AckerApple** [comment]
I have created an PR but i have some pipeline issues. It such a small change so if you can offer help please do

https://github.com/golevelup/nestjs/pull/872

My auto linter got involved so rollback changes

**Comment by AckerApple** [comment]
I think @underfisk has everything under control. I'm at a company that had not updated dependencies for quite sometime and AmqpConnection did not throw the error it currently does so I looked up how the old code worked (without any config argument) and I am posting evidence of that for future referencing, below

code links below show where config.logger was NOT used right away in constructor

Old code link here:
https://github.com/golevelup/nestjs/commit/305922e97453956da0177c44a1415c4720e9db01

![image](https://github.com/user-attachments/assets/73863cba-6dcb-4411-bb17-134afaae2a41)

![image](https://github.com/user-attachments/assets/c5ed9082-7429-4fba-93ed-c1faff1666ab)

**Comment by AckerApple** [comment]
@underfisk how might I install the fix into my company's project? If release to npm will be soon soon, I can wait but if you have a recommendation I would appreciate it such as an install by github path

**Comment by underfisk** [comment]
@AckerApple Let's see if @WonderPanda can produce a release soon, we had some issues with the publish process but should be good now.

**Comment by WonderPanda** [comment]
Just published. The new version is `@golevelup/nestjs-rabbitmq@5.6.0`

**Comment by AckerApple** [comment]
I am totally 100% fixed! My updated server starts now!!! Thank you extra

@vane-tec details matter
